package org.ega_archive.elixircore.dto.message;

import org.ega_archive.elixircore.enums.MessageType;

import com.fasterxml.jackson.annotation.JsonTypeInfo;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Builder;

/**
 * Represents a message generated by any service.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
@Getter
@Setter
@Builder(builderMethodName = "messageBuilder")
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class ServiceMessage {

  private MessageHeader header;

  // Command or Event
  private MessageType messageType;
}
